spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.3.146/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/huaxutongxun/work/idea-workspace/sell/log
#  level:
#    com.yang.sell.LoggerTest: debug
  # file: /Users/huaxutongxun/work/idea-workspace/sell/log/sell.log

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: XXXXXXXXXXXXXX
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/huaxutongxun/study/h5.p12
  notifyUrl: http://yjl.natapp1.cc/notify
