spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.3.146/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#为null时json不显示
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.16.3.146
    port: 6379

#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/huaxutongxun/work/idea-workspace/sell/log
#  level:
#    com.yang.sell.LoggerTest: debug
  # file: /Users/huaxutongxun/work/idea-workspace/sell/log/sell.log

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: XXXXXXXXXXXXXX
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/huaxutongxun/study/h5.p12
  notifyUrl: http://yjl.natapp1.cc/notify

projectUrl:
  wechatMpAuthorize: http://yjl.natapp1.cc
  wechatOpenAuthorize: http://yjl.natapp1.cc
  sell: http://yjl.natapp1.cc
  otherWechatOpenAuthorize: http://sell.springboot.cn

#让mybatis显示sql语句
logging:
  level:
    com.yang.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml